Repository polyflix/frontend, pull requests merged in 2022-12, with the labels that each got.

#34 fix(locales): added i18n translation
  public/locales/en/courses.json
  public/locales/fr/courses.json
Labels: semver: patch

#41 fix(#13): private element of a collection can not be clicked
  src/modules/collections/components/CollectionTimeline/CollectionTimeline.component.tsx
  src/modules/collections/components/CollectionTimeline/ItemCollectionTimeline.component.tsx
Labels: action: review, semver: patch, priority: high, type: fix

#26 fix: update polyflix npm package
  .npmrc
  package-lock.json
  package.json
Labels: semver: patch

#46 chore: bump @polyflix packages
  apps/polyflix/package.json
  pnpm-lock.yaml
Labels: semver: patch

#44 test(e2e): utils for create account
  apps/polyflix/tests/global-setup.ts
  apps/polyflix/tests/spec/quizz/crud.spec.ts
  apps/polyflix/tests/spec/video/crud.spec.ts
  apps/polyflix/tests/util.ts
  tests/utils/create-accounts.spec.ts
  tests/utils/util.ts
Labels: semver: patch

#49 refactor: rework conditions for authentication / mock
  apps/polyflix/src/environments/environment.ts
  apps/polyflix/src/main.tsx
  apps/polyflix/src/modules/authentication/auth.router.tsx
  apps/polyflix/src/modules/authentication/pages/Mock.page.tsx
  apps/polyflix/src/modules/authentication/pages/Redirect.page.tsx
Labels: semver: minor

#52 fix: bad display of videos count
  apps/polyflix/public/locales/en/videos.json
  apps/polyflix/public/locales/fr/videos.json
Labels: semver: patch

#54 fix: remove empty search call on page load
  apps/polyflix/src/modules/search/services/search.service.ts
Labels: semver: minor

#55 fix: change keycloak environment variable
  apps/polyflix/src/environments/environment.ts
Labels: semver: patch, priority: high, type: fix

#56 fix: update API gateway port
  apps/polyflix/src/environments/environment.ts
Labels: semver: patch, priority: high, type: fix

#57 fix(auth): redirection works again in mock and regular mode
  apps/polyflix/src/main.tsx
  apps/polyflix/src/modules/authentication/auth.router.tsx
  apps/polyflix/src/modules/authentication/pages/Mock.page.tsx
  apps/polyflix/src/modules/authentication/pages/Redirect.page.tsx
Labels: action: review, bug, type: fix, semver: minor

#59 fix: package app on release
  .github/workflows/package.yml
  .github/workflows/release.yml
Labels: semver: patch
