Repository polyflix/frontend, pull requests merged in 2023-01, with the labels that each got.

#58 feat: refactor home page
  .github/workflows/pull_request.yml
  apps/polyflix/public/locales/en/common.json
  apps/polyflix/public/locales/en/home.json
  apps/polyflix/public/locales/en/videos.json
  apps/polyflix/public/locales/fr/common.json
  apps/polyflix/public/locales/fr/home.json
  apps/polyflix/public/locales/fr/videos.json
  apps/polyflix/src/environments/environment.ts
  apps/polyflix/src/modules/core/components/CardInformation/card-information.component.tsx
  apps/polyflix/src/modules/core/components/CardMenu/CardMenu.component.tsx
  apps/polyflix/src/modules/core/components/CourseCard/course-card.component.tsx
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.style.tsx
  apps/polyflix/src/modules/core/components/Dashboard/Sidebar/Sidebar.component.tsx
  apps/polyflix/src/modules/core/components/Dashboard/Sidebar/UserMinimalCard/UserMinimalCard.component.tsx
  apps/polyflix/src/modules/core/components/ElementLockIcon/element-lock-icon.component.tsx
  apps/polyflix/src/modules/core/components/ElementSmallTag/element-small-tag.component.tsx
  apps/polyflix/src/modules/core/components/ElementsRow/elements-row.component.tsx
  apps/polyflix/src/modules/core/components/Footer/footer.component.tsx
  apps/polyflix/src/modules/core/components/ImageCover/image-cover.component.tsx
  apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx
  apps/polyflix/src/modules/core/components/ListVideoCard/list-video-card.component.tsx
  apps/polyflix/src/modules/core/components/NullableTypography/nullable-typography.component.tsx
  apps/polyflix/src/modules/core/components/Page/Page.component.tsx
  apps/polyflix/src/modules/core/components/PageSection/page-section.component.tsx
  apps/polyflix/src/modules/core/components/Spotlight/Spotlight.style.tsx
  apps/polyflix/src/modules/core/components/UserDisplayName/user-display-name.tsx
  apps/polyflix/src/modules/core/components/VideoCard/video-card.component.tsx
  apps/polyflix/src/modules/core/components/VideoCardMenu/element-option.component.tsx
  apps/polyflix/src/modules/core/layouts/Dashboard/Dashboard.layout.tsx
  apps/polyflix/src/modules/core/layouts/Dashboard/Dashboard.style.tsx
  apps/polyflix/src/modules/core/pages/Home.page.tsx
  apps/polyflix/src/modules/core/utils/http-utils.ts
  apps/polyflix/src/modules/courses/models/course.model.ts
  apps/polyflix/src/modules/users/components/UserAvatar/UserAvatar.component.tsx
  apps/polyflix/src/modules/videos/components/VideoSliderCard/VideoSliderCard.component.tsx
  apps/polyflix/src/modules/videos/components/VideoSliderCard/VideoSliderCard.style.ts
  apps/polyflix/src/theme/overrides/Chip.component.tsx
  apps/polyflix/src/theme/overrides/index.tsx
  package.json
  packages/mock-server/fixtures/course.ts
  packages/mock-server/fixtures/video.ts
  packages/mock-server/index.ts
  pnpm-lock.yaml
Labels: semver: patch

#66 feat(#43): rework Home page
  apps/polyflix/index.html
  apps/polyflix/public/Polyflix-1200x628.png
  apps/polyflix/public/Polyflix-192x192.png
  apps/polyflix/public/favicon.ico
  apps/polyflix/public/logo192.png
  apps/polyflix/public/logo512.png
  apps/polyflix/public/robots.txt
Labels: semver: patch

#87 feat: add likes (#74)
  apps/polyflix/src/modules/core/components/ElementSmallTag/element-small-tag.component.tsx
  apps/polyflix/src/modules/core/components/Icon/Icon.component.tsx
  apps/polyflix/src/modules/core/components/VideoCard/video-card.component.tsx
Labels: semver: minor

#88 feat: home page searchbar v1 (#73)
  apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx
Labels: semver: minor

#85 fix: remve info button and padding on more-vert button (#76)
  apps/polyflix/src/modules/core/components/CardMenu/CardMenu.component.tsx
  apps/polyflix/src/modules/users/pages/ProfileVideos/ProfileVideos.page.tsx
Labels: semver: minor

#83 fix: typo (#77)
  apps/polyflix/public/locales/en/home.json
Labels: semver: patch

#82 feat: burger menu (#78)
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
Labels: semver: minor

#81 fix: handle close on click menu (#80)
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
Labels: semver: major

#84 feat: video views (#75)
  apps/polyflix/src/modules/core/components/VideoCard/video-card.component.tsx
Labels: semver: major

#89 fix: home page courses query page need to be 1 or more
  apps/polyflix/src/modules/core/pages/Home.page.tsx
Labels: semver: patch

#91 feat: add logout button (#68)
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
Labels: semver: patch

#90 feat: remove view from video list card (#75)
  apps/polyflix/src/modules/core/components/ListVideoCard/list-video-card.component.tsx
Labels: semver: minor

#97 fix(#96): redirection on mock server after login
  apps/polyflix/src/environments/environment.ts
  apps/polyflix/src/modules/authentication/pages/Mock.page.tsx
  packages/mock-server/index.ts
Labels: action: review, semver: patch, priority: high, type: fix

#100 fix(#92): profile page UI padding too large
  apps/polyflix/src/modules/core/components/Header/Header.component.tsx
  apps/polyflix/src/modules/users/pages/ProfileAttachments/ProfileAttachments.page.tsx
  apps/polyflix/src/modules/users/pages/ProfileCertifications/ProfileCertifications.page.tsx
  apps/polyflix/src/modules/users/pages/ProfileCollections/ProfileCollections.page.tsx
  apps/polyflix/src/modules/users/pages/ProfileCourses/ProfileCourses.page.tsx
  apps/polyflix/src/modules/users/pages/ProfileQuizzes/ProfileQuizzes.page.tsx
  apps/polyflix/src/modules/users/pages/ProfileVideos/ProfileVideos.page.tsx
Labels: semver: patch

#103 feat(video): view publisher profile
  apps/polyflix/public/locales/en/users.json
  apps/polyflix/public/locales/fr/users.json
  apps/polyflix/src/modules/core/components/CardInformation/card-information.component.tsx
Labels: semver: patch

#105 fix(#95): buttons style and padding improvements
  apps/polyflix/src/modules/videos/pages/[create-update].page.tsx
Labels: semver: patch

#109 fix(homepage): title ellipsis + wrap title + fix darkmode
  apps/polyflix/src/modules/core/components/Dashboard/Navbar/Navbar.component.tsx
  apps/polyflix/src/modules/core/components/Jumbotron/jumbotron.component.tsx
Labels: semver: patch

#107 feat: studio (#104)
  .dockerignore
  .github/workflows/package.yml
  Dockerfile.app
  apps/polyflix/Dockerfile
  apps/polyflix/package.json
  apps/studio/.docker/nginx.conf
  apps/studio/.gitignore
  apps/studio/Dockerfile
  apps/studio/index.html
  apps/studio/package.json
  apps/studio/public/vite.svg
  apps/studio/src/App.css
  apps/studio/src/App.tsx
  apps/studio/src/assets/react.svg
  apps/studio/src/index.css
  apps/studio/src/main.tsx
  apps/studio/src/vite-env.d.ts
  apps/studio/tsconfig.json
  apps/studio/tsconfig.node.json
  apps/studio/vite.config.ts
  pnpm-lock.yaml
Labels: semver: patch

#101 chore: update default environment to use devkit
  apps/polyflix/package.json
  apps/polyflix/src/environments/devkit.environment.ts
  apps/polyflix/src/environments/docker.environment.ts
Labels: priority: medium, action: review, semver: patch, type: chore

#111 feat: studio light base + video part base (#110)
  apps/studio/.eslintrc.cjs
  apps/studio/.prettierrc
  apps/studio/package.json
  apps/studio/src/App.css
  apps/studio/src/App.tsx
  apps/studio/src/components/ghost-list.component.tsx
  apps/studio/src/components/header.component.tsx
  apps/studio/src/components/loading-fallback.component.tsx
  apps/studio/src/components/quick-access-card.component.tsx
  apps/studio/src/components/quick-link.component.tsx
  apps/studio/src/index.css
  apps/studio/src/layouts/StudioLayout.tsx
  apps/studio/src/main.routing.tsx
  apps/studio/src/main.tsx
  apps/studio/src/pages/home/Home.error.tsx
  apps/studio/src/pages/home/Home.loading.tsx
  apps/studio/src/pages/home/Home.tsx
  apps/studio/src/pages/video/Video.layout.tsx
  apps/studio/src/pages/video/Video.routing.tsx
  apps/studio/src/pages/video/Video.tsx
  apps/studio/src/pages/video/form/VideoForm.tsx
  apps/studio/src/pages/video/view/VideoView.error.tsx
  apps/studio/src/pages/video/view/VideoView.loading.tsx
  apps/studio/src/pages/video/view/VideoView.tsx
  packages/ui-lib/components/Icon/icon.component.tsx
  packages/ui-lib/components/LinkRouter/link-router.component.tsx
  packages/ui-lib/components/RouterBreadcrumbs/router-breadcrumbs.component.tsx
  packages/ui-lib/components/index.ts
  packages/ui-lib/hook/index.ts
  packages/ui-lib/hook/use-pop-over-modal.hook.tsx
  packages/ui-lib/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  shared/api/index.ts
  shared/api/package.json
  shared/api/src/http.service.ts
  shared/api/src/video.service.ts
  shared/theme/breakpoints.config.ts
  shared/theme/breakpoints.ts
  shared/theme/globalStyles.tsx
  shared/theme/index.ts
  shared/theme/overrides/Avatar.component.tsx
  shared/theme/overrides/Button.component.tsx
  shared/theme/overrides/Chip.component.tsx
  shared/theme/overrides/Menu.component.tsx
  shared/theme/overrides/Typography.component.tsx
  shared/theme/overrides/index.tsx
  shared/theme/package-lock.json
  shared/theme/package.json
  shared/theme/palette.config.ts
  shared/theme/shadows.config.ts
  shared/theme/shapes.config.ts
  shared/theme/shapes.ts
  shared/theme/theme.tsx
  shared/theme/typography.config.ts
  shared/utils/gui.utils.ts
  shared/utils/index.ts
  shared/utils/package.json
Labels: semver: major
